struct {
	char *ext;
	char *filetype;
} extensions [] = {
	{"gif", "image/gif"	},  
	{"jpg", "image/jpeg"}, 
	{"jpeg", "image/jpeg"},
	{"png", "image/png"	},  
	{"zip", "application/zip"	},  
	{"gz", "application/gzip" 	},  
	{"tar", "application/tar"	},  
	{"htm", "text/html"	},  
	{"html", "text/html"	},  
	{"php", "text/php"	},  
	{"cgi", "text/cgi" 	},  
	{"asp", "text/asp"  	},  
	{"jsp", "image/jsp"	},  
	{"xml", "text/xml" 	},  
	{"js", "text/js"   	},
	{"css", "text/css" 	}, 
	{"c", "text/plain" 	},
	{"h", "text/plain" 	},
	{"txt", "text/plain"},
	{"sh", "text/plain"	},
	{"ttf", "font/ttf"	},
	{"ogg", "audio/ogg"	},
	{"mp3", "audio/mpeg"},
	{"woff", "application/font-woff"},
	{"flv", "video/x-flv"	},
	{"mp4", "video/mp4"	},
	{"webm", "video/webm"	},
	{"swf", "application/x-shockwave-flash"	},
	{"iso", "application/octet-stream"	},
	{"exe", "application/octet-stream"	},
	{"cso", "application/octet-stream"	},
        {"xz", "application/x-xz"	},
        {"bz2", "application/bzip2"	},
        {"docx", "application/msword"	},
        {"avi", "video/avi"	},
        {"xhtml", "text/xhtml"	},
        {"pl", "text/plain"	},
	{"rar", "application/x-rar"	},
	{"7z", "application/x-7z"	},
        {"cpp", "text/plain"	},
        {"hpp", "text/plain"	},
        {"ogv", "video/ogg" },
        {"patch", "text/plain" },
        {"svg", "image/svg" },
        {"ico", "image/x-icon" },
	{0,0} 
};
