#!/bin/sh
# Start / Stop chttpd (For unix)

CONFIG="/etc/chttpd.conf"
START_MSG="Starting CHTTPD"
STOP_MSG="Stopping CHTTPD Processes"
ERROR_MSG="Error, Usage: {start|stop}"

case $1 in
	start) echo $START_MSG; chttpd ${CONFIG};;
	stop) echo $STOP_MSG; killall chttpd;;
	*) echo $ERROR_MSG;;
esac
